name: Docs

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -e ".[docs]"
          pip install mace-torch
          python -m ipykernel install --user --name python3

      - name: Convert and execute Si64.py
        run: |
          jupytext --to notebook --execute example/Si64.py -o docs/examples/Si64.ipynb
        env:
          CI: "true"

      - name: Build docs
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
